In [1]:
from IPython.display import display_html
def display_side_by_side(*args):
    html_str=''
    for df in args:
        html_str+=df.to_html()
    display_html(html_str.replace('table','table style="display:inline"'),raw=True)

# Data Input

In [2]:
# From Kaggle
# https://www.kaggle.com/mczielinski/bitcoin-historical-data
import pandas as pd
import os

dataset_path = '../files/datasets/kaggle/'
dataset_path = './data/'

print('Data listing:')
print(os.listdir(dataset_path))

# Import the dataset and encode the date
header = ['time', 'open', 'high', 'low', 'close', 'volume', 'volume_currency', 'weighted_price']
kaggle_df = pd.read_csv(dataset_path + 'bitcoin.csv', names=header, header=0)
# kaggle_df['date'] = pd.to_datetime(kaggle_df['Timestamp'],unit='s').dt.date
# group = kaggle_df.groupby('date')
# Real_Price = group['Weighted_Price'].mean()

print('DataFrame:')
kaggle_df.head()

Data listing:
['bit2.csv', 'bitcoin_eval.csv', '^GSPC_2011.csv', 'bit1.csv', 'bitcoin.csv', 'bitcoin-historical-data', '^GSPC.csv']
DataFrame:

,time,open,high,low,close,volume,volume_currency,weighted_price
0,1417411980,300.0,300.0,300.0,300.0,0.01,3.0,300.0
1,1417412040,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1417412100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1417412160,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1417412220,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
len(kaggle_df)

2016354

In [5]:
kaggle_df.dropna(inplace=True)
# Convert to human readable date
kaggle_df['time'] = pd.to_datetime(kaggle_df['time'], unit='s')

In [6]:
kaggle_df

,time,open,high,low,close,volume,volume_currency,weighted_price
0,2014-12-01 05:33:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
7,2014-12-01 05:40:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
51,2014-12-01 06:24:00,370.00,370.00,370.00,370.00,0.010000,3.700000,370.000000
77,2014-12-01 06:50:00,370.00,370.00,370.00,370.00,0.026556,9.825550,370.000000
1436,2014-12-02 05:29:00,377.00,377.00,377.00,377.00,0.010000,3.770000,377.000000
1766,2014-12-02 10:59:00,377.75,378.00,377.75,378.00,4.000000,1511.937500,377.984375
1771,2014-12-02 11:04:00,378.00,378.00,378.00,378.00,4.900000,1852.200000,378.000000
1772,2014-12-02 11:05:00,378.00,378.00,378.00,378.00,5.200000,1965.600000,378.000000
2230,2014-12-02 18:43:00,378.00,378.00,378.00,378.00,0.100000,37.800000,378.000000
2245,2014-12-02 18:58:00,378.00,378.00,378.00,378.00,0.793600,299.980800,378.000000
2309,2014-12-02 20:02:00,378.00,378.00,378.00,378.00,0.010000,3.780000,378.000000
2882,2014-12-03 05:35:00,377.90,377.90,377.90,377.90,0.010000,3.779000,377.900000
2898,2014-12-03 05:51:00,378.00,378.00,378.00,378.00,0.066084,24.979828,378.000000
2915,2014-12-03 06:08:00,378.00,378.00,378.00,378.00,0.010524,3.978155,378.000000
3659,2014-12-03 18:32:00,378.00,378.00,378.00,378.00,0.350000,132.300000,378.000000
3753,2014-12-03 20:06:00,377.01,377.01,377.01,377.01,0.100000,37.701000,377.010000
3922,2014-12-03 22:55:00,378.00,378.00,378.00,378.00,0.010000,3.780000,378.000000
4095,2014-12-04 01:48:00,377.10,377.10,377.10,377.10,0.010000,3.771000,377.100000
4096,2014-12-06 01:41:00,378.00,378.00,378.00,378.00,0.015000,5.670000,378.000000
4097,2014-12-08 22:26:00,375.01,375.01,375.00,375.00,0.235000,88.125100,375.000426
4098,2014-12-10 02:42:00,398.00,398.00,398.00,398.00,0.010000,3.980000,398.000000
4099,2014-12-10 02:43:00,360.50,360.50,360.50,360.50,0.010000,3.605000,360.500000
4100,2014-12-12 03:30:00,379.00,379.00,379.00,379.00,0.050000,18.950000,379.000000
4103,2014-12-12 03:33:00,364.99,364.99,364.99,364.99,0.010000,3.649900,364.990000
4114,2014-12-12 03:44:00,360.50,360.50,360.00,360.00,1.090000,392.895000,360.454128
4116,2014-12-12 03:46:00,350.00,350.00,350.00,350.00,2.000000,700.000000,350.000000
4117,2014-12-18 20:56:00,345.00,345.00,340.00,340.00,2.000000,685.000000,342.500000
4118,2015-01-08 01:24:00,360.00,360.00,360.00,360.00,0.010000,3.600000,360.000000
4121,2015-01-08 01:27:00,271.84,276.34,271.84,276.34,0.020000,5.481800,274.090000
4122,2015-01-08 01:28:00,295.19,319.84,271.60,271.60,0.030000,8.866300,295.543333
...,...,...,...,...,...,...,...,...
2016324,2018-11-10 23:31:00,6361.19,6361.20,6361.19,6361.20,1.522197,9682.999649,6361.199726
2016325,2018-11-10 23:32:00,6361.20,6361.20,6357.00,6357.01,4.325664,27512.756078,6360.355111
2016326,2018-11-10 23:33:00,6357.01,6357.01,6355.77,6355.78,0.749786,4765.588930,6355.935270
2016327,2018-11-10 23:34:00,6355.78,6355.78,6355.77,6355.77,1.360339,8646.003296,6355.772404
2016328,2018-11-10 23:35:00,6355.78,6355.78,6353.92,6353.93,5.583475,35483.281042,6355.052698
2016329,2018-11-10 23:36:00,6353.93,6353.93,6350.11,6350.12,0.983608,6249.117576,6353.260670
2016330,2018-11-10 23:37:00,6350.11,6352.00,6350.11,6351.99,0.967309,6143.803988,6351.437891
2016331,2018-11-10 23:38:00,6351.99,6352.45,6351.99,6352.45,0.568356,3610.232022,6352.055483
2016332,2018-11-10 23:39:00,6352.45,6353.91,6352.44,6352.48,0.434861,2762.454480,6352.504330
2016333,2018-11-10 23:40:00,6352.47,6352.98,6352.47,6352.98,0.460858,2927.698392,6352.710465
2016334,2018-11-10 23:41:00,6352.98,6355.00,6352.97,6355.00,0.623509,3961.930517,6354.248438
2016335,2018-11-10 23:42:00,6355.45,6355.78,6355.45,6355.78,0.768663,4885.446949,6355.773470
2016336,2018-11-10 23:43:00,6355.77,6355.78,6355.77,6355.78,1.134108,7208.139233,6355.776417
2016337,2018-11-10 23:44:00,6355.78,6355.78,6355.77,6355.78,1.108281,7043.983962,6355.774530
2016338,2018-11-10 23:45:00,6355.77,6355.77,6354.99,6355.00,0.735974,4677.127042,6355.020128
2016339,2018-11-10 23:46:00,6355.00,6355.00,6350.10,6352.19,1.034777,6574.089322,6353.143079
2016340,2018-11-10 23:47:00,6352.20,6352.20,6350.49,6351.30,0.570445,3623.331048,6351.763306
2016341,2018-11-10 23:48:00,6351.29,6351.30,6350.00,6350.00,37.939623,240941.872660,6350.665900
2016342,2018-11-10 23:49:00,6350.00,6350.01,6347.41,6347.41,9.188776,58342.312389,6349.302022
2016343,2018-11-10 23:50:00,6347.42,6347.42,6347.41,6347.41,0.432489,2745.192137,6347.419302
2016344,2018-11-10 23:51:00,6347.41,6347.42,6347.41,6347.41,0.492783,3127.896578,6347.414530
2016345,2018-11-10 23:52:00,6347.42,6347.42,6347.41,6347.42,0.337241,2140.610218,6347.418909
2016346,2018-11-10 23:53:00,6347.41,6347.42,6347.41,6347.42,0.704688,4472.946150,6347.416509
2016347,2018-11-10 23:54:00,6347.42,6347.42,6347.41,6347.42,1.124513,7137.751098,6347.415255
2016348,2018-11-10 23:55:00,6347.41,6347.42,6347.41,6347.42,1.608627,10210.630629,6347.418861
2016349,2018-11-10 23:56:00,6347.41,6347.42,6347.41,6347.42,0.484960,3078.241490,6347.417225
2016350,2018-11-10 23:57:00,6347.41,6347.42,6347.41,6347.42,0.770757,4892.318043,6347.419294
2016351,2018-11-10 23:58:00,6347.41,6347.42,6347.41,6347.42,1.213145,7700.341614,6347.418653
2016352,2018-11-10 23:59:00,6347.41,6347.42,6347.41,6347.42,1.714091,10880.053958,6347.418881
2016353,2018-11-11 00:00:00,6347.42,6347.42,6347.41,6347.42,0.489324,3105.944897,6347.417439

In [ ]:
# From CCXT
import pandas as pd
import ccxt

broker = 'binance'

exchange = getattr(ccxt, broker)()

# exchange.load_markets()
# print(f'Available symbols for {broker} are:')
# for key in exchange.symbols:
#     print('  - ' + key)

pair = 'BTC/USDT'

#Timeframes: '1m', '5m', '15m', '30m', '1h', '2h', '3h', '4h', '6h', '12h', '1d', '1M', '1y'
time_frame = '1h'

data = exchange.fetch_ohlcv(pair, time_frame)

header = ['time', 'open', 'high', 'low', 'close', 'volume']
df = pd.DataFrame(data, columns=header)

print( f'Last Price is {df.loc[len(df) - 1]["close"]} ' )

In [ ]:
# Read the file
btc_actual = pd.read_csv('./files/datasets/binance-BTCUSDT-1m.csv', names=['time', 'open', 'high', 'low', 'close', 'volume'], header=0)
print(f'btc df lenght={len(btc_actual)}')

In [ ]:
display_side_by_side(btc_actual.tail(10))

Tutorial data

In [ ]:
import pandas as pd
ltc = pd.read_csv('../files/datasets/crypto_data/LTC-USD.csv', names=['time', 'low', 'high', 'open', 'close', 'volume'])
btc = pd.read_csv('../files/datasets/crypto_data/BTC-USD.csv', names=['time', 'low', 'high', 'open', 'close', 'volume'])
eth = pd.read_csv('../files/datasets/crypto_data/ETH-USD.csv', names=['time', 'low', 'high', 'open', 'close', 'volume'])
bch = pd.read_csv('../files/datasets/crypto_data/BCH-USD.csv', names=['time', 'low', 'high', 'open', 'close', 'volume'])
{'ltc':len(ltc), 'btc':len(btc), 'eth':len(eth), 'bch':len(bch)}

In [ ]:
display_side_by_side(ltc.head(10), btc.head(10), eth.head(10), bch.head(10))

# Join more data

Bitcoin

In [ ]:
display_side_by_side(btc_actual.head(10), btc.head(10))

In [ ]:
# Remove the last 3 zeros
btc_actual['time'] = btc_actual['time']/1000

In [ ]:
# Convert to human readable date
btc_actual['time'] = pd.to_datetime(btc_actual['time'], unit='s')
btc['time'] = pd.to_datetime(btc['time'], unit='s')

In [ ]:
display_side_by_side(btc_actual.tail(10), btc.head(10))

In [ ]:
btc = btc.append(btc_actual)

# Preprocess

In [7]:
kaggle_df.set_index('time', inplace=True)

In [8]:
# Select the Data
main_df = kaggle_df
ratio = 'BTC-USD'
main_df.rename(columns={'close':f'{ratio}_close', 'volume':f'{ratio}_volume'}, inplace=True)
# main_df.set_index('time', inplace=True)
#main_df = main_df[[f'{ratio}_close', f'{ratio}_volume']]

In [9]:
def classify(current, future):
    # If the price is higher in the future
    # then, with the current data, label
    # whether is a buy or sell oportunity
    if (float(future) > float(current)):
        return 1 #Buy chance
    else:
        return 0 #Sell chance

In [10]:
# For any supervised recurrent ML model, we need two things:
# Sequences and Targets
# Starting Constants

# Use the last 60 minutes of all the datasets to predict 3 minutes in the future
SEQ_LEN = 60
FUTURE_PERIOD_PREDICT = 3 #3 minutes
RATIO_TO_PREDICT = 'BTC-USD'

In [11]:
main_df

,open,high,low,BTC-USD_close,BTC-USD_volume,volume_currency,weighted_price
time,,,,,,,
2014-12-01 05:33:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 05:40:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000
2014-12-01 06:24:00,370.00,370.00,370.00,370.00,0.010000,3.700000,370.000000
2014-12-01 06:50:00,370.00,370.00,370.00,370.00,0.026556,9.825550,370.000000
2014-12-02 05:29:00,377.00,377.00,377.00,377.00,0.010000,3.770000,377.000000
2014-12-02 10:59:00,377.75,378.00,377.75,378.00,4.000000,1511.937500,377.984375
2014-12-02 11:04:00,378.00,378.00,378.00,378.00,4.900000,1852.200000,378.000000
2014-12-02 11:05:00,378.00,378.00,378.00,378.00,5.200000,1965.600000,378.000000
2014-12-02 18:43:00,378.00,378.00,378.00,378.00,0.100000,37.800000,378.000000
2014-12-02 18:58:00,378.00,378.00,378.00,378.00,0.793600,299.980800,378.000000
2014-12-02 20:02:00,378.00,378.00,378.00,378.00,0.010000,3.780000,378.000000
2014-12-03 05:35:00,377.90,377.90,377.90,377.90,0.010000,3.779000,377.900000
2014-12-03 05:51:00,378.00,378.00,378.00,378.00,0.066084,24.979828,378.000000
2014-12-03 06:08:00,378.00,378.00,378.00,378.00,0.010524,3.978155,378.000000
2014-12-03 18:32:00,378.00,378.00,378.00,378.00,0.350000,132.300000,378.000000
2014-12-03 20:06:00,377.01,377.01,377.01,377.01,0.100000,37.701000,377.010000
2014-12-03 22:55:00,378.00,378.00,378.00,378.00,0.010000,3.780000,378.000000
2014-12-04 01:48:00,377.10,377.10,377.10,377.10,0.010000,3.771000,377.100000
2014-12-06 01:41:00,378.00,378.00,378.00,378.00,0.015000,5.670000,378.000000
2014-12-08 22:26:00,375.01,375.01,375.00,375.00,0.235000,88.125100,375.000426
2014-12-10 02:42:00,398.00,398.00,398.00,398.00,0.010000,3.980000,398.000000
2014-12-10 02:43:00,360.50,360.50,360.50,360.50,0.010000,3.605000,360.500000
2014-12-12 03:30:00,379.00,379.00,379.00,379.00,0.050000,18.950000,379.000000
2014-12-12 03:33:00,364.99,364.99,364.99,364.99,0.010000,3.649900,364.990000
2014-12-12 03:44:00,360.50,360.50,360.00,360.00,1.090000,392.895000,360.454128
2014-12-12 03:46:00,350.00,350.00,350.00,350.00,2.000000,700.000000,350.000000
2014-12-18 20:56:00,345.00,345.00,340.00,340.00,2.000000,685.000000,342.500000
2015-01-08 01:24:00,360.00,360.00,360.00,360.00,0.010000,3.600000,360.000000
2015-01-08 01:27:00,271.84,276.34,271.84,276.34,0.020000,5.481800,274.090000
2015-01-08 01:28:00,295.19,319.84,271.60,271.60,0.030000,8.866300,295.543333
...,...,...,...,...,...,...,...
2018-11-10 23:31:00,6361.19,6361.20,6361.19,6361.20,1.522197,9682.999649,6361.199726
2018-11-10 23:32:00,6361.20,6361.20,6357.00,6357.01,4.325664,27512.756078,6360.355111
2018-11-10 23:33:00,6357.01,6357.01,6355.77,6355.78,0.749786,4765.588930,6355.935270
2018-11-10 23:34:00,6355.78,6355.78,6355.77,6355.77,1.360339,8646.003296,6355.772404
2018-11-10 23:35:00,6355.78,6355.78,6353.92,6353.93,5.583475,35483.281042,6355.052698
2018-11-10 23:36:00,6353.93,6353.93,6350.11,6350.12,0.983608,6249.117576,6353.260670
2018-11-10 23:37:00,6350.11,6352.00,6350.11,6351.99,0.967309,6143.803988,6351.437891
2018-11-10 23:38:00,6351.99,6352.45,6351.99,6352.45,0.568356,3610.232022,6352.055483
2018-11-10 23:39:00,6352.45,6353.91,6352.44,6352.48,0.434861,2762.454480,6352.504330
2018-11-10 23:40:00,6352.47,6352.98,6352.47,6352.98,0.460858,2927.698392,6352.710465
2018-11-10 23:41:00,6352.98,6355.00,6352.97,6355.00,0.623509,3961.930517,6354.248438
2018-11-10 23:42:00,6355.45,6355.78,6355.45,6355.78,0.768663,4885.446949,6355.773470
2018-11-10 23:43:00,6355.77,6355.78,6355.77,6355.78,1.134108,7208.139233,6355.776417
2018-11-10 23:44:00,6355.78,6355.78,6355.77,6355.78,1.108281,7043.983962,6355.774530
2018-11-10 23:45:00,6355.77,6355.77,6354.99,6355.00,0.735974,4677.127042,6355.020128
2018-11-10 23:46:00,6355.00,6355.00,6350.10,6352.19,1.034777,6574.089322,6353.143079
2018-11-10 23:47:00,6352.20,6352.20,6350.49,6351.30,0.570445,3623.331048,6351.763306
2018-11-10 23:48:00,6351.29,6351.30,6350.00,6350.00,37.939623,240941.872660,6350.665900
2018-11-10 23:49:00,6350.00,6350.01,6347.41,6347.41,9.188776,58342.312389,6349.302022
2018-11-10 23:50:00,6347.42,6347.42,6347.41,6347.41,0.432489,2745.192137,6347.419302
2018-11-10 23:51:00,6347.41,6347.42,6347.41,6347.41,0.492783,3127.896578,6347.414530
2018-11-10 23:52:00,6347.42,6347.42,6347.41,6347.42,0.337241,2140.610218,6347.418909
2018-11-10 23:53:00,6347.41,6347.42,6347.41,6347.42,0.704688,4472.946150,6347.416509
2018-11-10 23:54:00,6347.42,6347.42,6347.41,6347.42,1.124513,7137.751098,6347.415255
2018-11-10 23:55:00,6347.41,6347.42,6347.41,6347.42,1.608627,10210.630629,6347.418861
2018-11-10 23:56:00,6347.41,6347.42,6347.41,6347.42,0.484960,3078.241490,6347.417225
2018-11-10 23:57:00,6347.41,6347.42,6347.41,6347.42,0.770757,4892.318043,6347.419294
2018-11-10 23:58:00,6347.41,6347.42,6347.41,6347.42,1.213145,7700.341614,6347.418653
2018-11-10 23:59:00,6347.41,6347.42,6347.41,6347.42,1.714091,10880.053958,6347.418881
2018-11-11 00:00:00,6347.42,6347.42,6347.41,6347.42,0.489324,3105.944897,6347.417439

In [12]:
# Create the future column based on the period which we want to predict
main_df['future'] = main_df[f'{RATIO_TO_PREDICT}_close'].shift(-FUTURE_PERIOD_PREDICT)

In [13]:
# Create the target column
main_df['target'] = list(map(classify, main_df[f'{RATIO_TO_PREDICT}_close'], main_df["future"]))

In [14]:
main_df.columns

Index(['open', 'high', 'low', 'BTC-USD_close', 'BTC-USD_volume',
       'volume_currency', 'weighted_price', 'future', 'target'],
      dtype='object')

In [15]:
main_df[[f'{RATIO_TO_PREDICT}_close','future', 'target', 'low', 'high', 'open', f'{RATIO_TO_PREDICT}_volume']].head(5)

,BTC-USD_close,future,target,low,high,open,BTC-USD_volume
time,,,,,,,
2014-12-01 05:33:00,300.0,370.0,1,300.0,300.0,300.0,0.010000
2014-12-01 05:40:00,300.0,377.0,1,300.0,300.0,300.0,0.010000
2014-12-01 06:24:00,370.0,378.0,1,370.0,370.0,370.0,0.010000
2014-12-01 06:50:00,370.0,378.0,1,370.0,370.0,370.0,0.026556
2014-12-02 05:29:00,377.0,378.0,1,377.0,377.0,377.0,0.010000


Take the out of sample test data. Chunk of data in the future. Imagine that we are training in a data that 5% less of what we have and then test the model against this 5%

In [16]:
times = sorted(main_df.index.values)
last_5pct = times[-int(0.05 * len(times))]

In [17]:
# Separate the out-of-sample data (last 5%) and the training data
validation_main_df = main_df[(main_df.index >= last_5pct)]
main_df = main_df[(main_df.index < last_5pct)]

In [18]:
main_df

,open,high,low,BTC-USD_close,BTC-USD_volume,volume_currency,weighted_price,future,target
time,,,,,,,,,
2014-12-01 05:33:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000,370.00,1
2014-12-01 05:40:00,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000,377.00,1
2014-12-01 06:24:00,370.00,370.00,370.00,370.00,0.010000,3.700000,370.000000,378.00,1
2014-12-01 06:50:00,370.00,370.00,370.00,370.00,0.026556,9.825550,370.000000,378.00,1
2014-12-02 05:29:00,377.00,377.00,377.00,377.00,0.010000,3.770000,377.000000,378.00,1
2014-12-02 10:59:00,377.75,378.00,377.75,378.00,4.000000,1511.937500,377.984375,378.00,0
2014-12-02 11:04:00,378.00,378.00,378.00,378.00,4.900000,1852.200000,378.000000,378.00,0
2014-12-02 11:05:00,378.00,378.00,378.00,378.00,5.200000,1965.600000,378.000000,378.00,0
2014-12-02 18:43:00,378.00,378.00,378.00,378.00,0.100000,37.800000,378.000000,377.90,0
2014-12-02 18:58:00,378.00,378.00,378.00,378.00,0.793600,299.980800,378.000000,378.00,0
2014-12-02 20:02:00,378.00,378.00,378.00,378.00,0.010000,3.780000,378.000000,378.00,0
2014-12-03 05:35:00,377.90,377.90,377.90,377.90,0.010000,3.779000,377.900000,378.00,1
2014-12-03 05:51:00,378.00,378.00,378.00,378.00,0.066084,24.979828,378.000000,377.01,0
2014-12-03 06:08:00,378.00,378.00,378.00,378.00,0.010524,3.978155,378.000000,378.00,0
2014-12-03 18:32:00,378.00,378.00,378.00,378.00,0.350000,132.300000,378.000000,377.10,0
2014-12-03 20:06:00,377.01,377.01,377.01,377.01,0.100000,37.701000,377.010000,378.00,1
2014-12-03 22:55:00,378.00,378.00,378.00,378.00,0.010000,3.780000,378.000000,375.00,0
2014-12-04 01:48:00,377.10,377.10,377.10,377.10,0.010000,3.771000,377.100000,398.00,1
2014-12-06 01:41:00,378.00,378.00,378.00,378.00,0.015000,5.670000,378.000000,360.50,0
2014-12-08 22:26:00,375.01,375.01,375.00,375.00,0.235000,88.125100,375.000426,379.00,1
2014-12-10 02:42:00,398.00,398.00,398.00,398.00,0.010000,3.980000,398.000000,364.99,0
2014-12-10 02:43:00,360.50,360.50,360.50,360.50,0.010000,3.605000,360.500000,360.00,0
2014-12-12 03:30:00,379.00,379.00,379.00,379.00,0.050000,18.950000,379.000000,350.00,0
2014-12-12 03:33:00,364.99,364.99,364.99,364.99,0.010000,3.649900,364.990000,340.00,0
2014-12-12 03:44:00,360.50,360.50,360.00,360.00,1.090000,392.895000,360.454128,360.00,0
2014-12-12 03:46:00,350.00,350.00,350.00,350.00,2.000000,700.000000,350.000000,276.34,0
2014-12-18 20:56:00,345.00,345.00,340.00,340.00,2.000000,685.000000,342.500000,271.60,0
2015-01-08 01:24:00,360.00,360.00,360.00,360.00,0.010000,3.600000,360.000000,344.67,0
2015-01-08 01:27:00,271.84,276.34,271.84,276.34,0.020000,5.481800,274.090000,305.38,1
2015-01-08 01:28:00,295.19,319.84,271.60,271.60,0.030000,8.866300,295.543333,270.35,0
...,...,...,...,...,...,...,...,...,...
2018-09-05 16:58:00,6902.00,6904.99,6889.53,6904.99,48.387851,333790.430270,6898.228017,6897.00,0
2018-09-05 16:59:00,6905.00,6918.80,6904.99,6918.01,47.382403,327677.483420,6915.594424,6904.90,0
2018-09-05 17:00:00,6918.01,6918.01,6907.00,6907.00,21.511032,148687.649890,6912.157915,6901.00,0
2018-09-05 17:01:00,6907.00,6907.01,6897.00,6897.00,15.145324,104548.671020,6903.033182,6892.77,0
2018-09-05 17:02:00,6897.00,6904.91,6896.40,6904.90,27.863258,192251.855710,6899.834079,6878.07,0
2018-09-05 17:03:00,6904.91,6904.91,6901.00,6901.00,6.483157,44745.771142,6901.849415,6890.01,0
2018-09-05 17:04:00,6901.01,6901.01,6892.76,6892.77,7.921998,54640.580072,6897.323543,6887.79,0
2018-09-05 17:05:00,6892.76,6892.77,6878.06,6878.07,36.753758,253053.309370,6885.100247,6884.97,1
2018-09-05 17:06:00,6878.06,6890.01,6869.00,6890.01,51.649478,354977.165280,6872.812309,6895.00,1
2018-09-05 17:07:00,6890.01,6893.88,6887.78,6887.79,14.746436,101638.776590,6892.430020,6900.00,1
2018-09-05 17:08:00,6887.78,6887.79,6875.00,6884.97,12.440860,85606.357421,6881.064479,6893.88,1
2018-09-05 17:09:00,6885.26,6895.00,6885.26,6895.00,32.310087,222670.858670,6891.682381,6891.00,0
2018-09-05 17:10:00,6895.00,6900.00,6895.00,6900.00,38.182310,263397.053070,6898.405333,6900.99,1
2018-09-05 17:11:00,6900.00,6900.00,6890.00,6893.88,19.723856,136042.775850,6897.372298,6901.00,1
2018-09-05 17:12:00,6893.88,6893.88,6884.00,6891.00,8.383090,57744.478416,6888.209117,6900.99,1
2018-09-05 17:13:00,6890.99,6901.00,6890.99,6900.99,21.500557,148280.309940,6896.579965,6901.00,1
2018-09-05 17:14:00,6901.00,6901.00,6900.99,6901.00,7.150055,49342.513160,6900.997726,6894.48,0
2018-09-05 17:15:00,6901.00,6904.94,6900.99,6900.99,13.133279,90650.262169,6902.332992,6889.51,0
2018-09-05 17:16:00,6901.00,6901.00,6900.99,6901.00,14.523272,100225.055550,6900.996958,6893.87,0
2018-09-05 17:17:00,6901.00,6901.00,6886.00,6894.48,29.175443,201246.902450,6897.818215,6880.01,0
2018-09-05 17:18:00,6894.48,6894.48,6889.50,6889.51,3.575898,24636.901802,6889.709521,6885.83,0
2018-09-05 17:19:00,6889.26,6893.87,6888.00,6893.87,7.397644,50968.884800,6889.880724,6890.00,0
2018-09-05 17:20:00,6893.87,6893.87,6880.00,6880.01,8.419348,57982.562797,6886.823152,6895.00,1
2018-09-05 17:21:00,6880.00,6887.31,6880.00,6885.83,16.297096,112201.021810,6884.724938,6894.99,1
2018-09-05 17:22:00,6885.83,6890.00,6885.82,6890.00,13.196571,90886.228860,6887.109660,6894.01,1
2018-09-05 17:23:00,6889.99,6895.00,6889.99,6895.00,10.839125,74722.773818,6893.801231,6886.42,0
2018-09-05 17:24:00,6895.00,6895.00,6894.99,6894.99,3.240664,22344.357622,6894.993583,6893.86,0
2018-09-05 17:25:00,6895.00,6895.00,6894.00,6894.01,5.047342,34800.167370,6894.751157,6893.87,0
2018-09-05 17:26:00,6894.00,6894.01,6885.01,6886.42,5.748396,39586.880307,6886.595801,6900.00,1
2018-09-05 17:27:00,6886.42,6893.87,6886.41,6893.86,4.992931,34395.549286,6888.848733,6900.99,1

In [19]:
# Function to clean, scale and normalize the data

from sklearn import preprocessing
from collections import deque
import random
import numpy as np

def preprocess_df(df):
    df = df.drop("future", 1)  # don't need this anymore.

    for col in df.columns:  # go through all of the columns
        if col != "target":  # normalize all ... except for the target itself!
            df[col] = df[col].pct_change()  # pct change "normalizes" the different currencies (each crypto coin has vastly diff values, we're really more interested in the other coin's movements)
            df = df.replace([np.inf, -np.inf], np.nan) # Change the inf values to nan df.dropna(inplace=True)  # remove the nas created by pct_change
            df[col] = preprocessing.scale(df[col].values)  # scale between 0 and 1.
    
    df.replace([np.inf, -np.inf], np.nan) # Change the inf values to nan
    df.dropna(inplace=True)  # cleanup again... jic.

    sequential_data = []  # this is a list that will CONTAIN the sequences
    prev_days = deque(maxlen=SEQ_LEN)  # These will be our actual sequences. They are made with deque, which keeps the maximum length by popping out older values as new ones come in

    for i in df.values:  # iterate over the values
        prev_days.append([n for n in i[:-1]])  # store all but the target
        if len(prev_days) == SEQ_LEN:  # make sure we have 60 sequences!
            sequential_data.append([np.array(prev_days), i[-1]])  # append those bad boys!

    random.shuffle(sequential_data)  # shuffle for good measure.

    buys = []  # list that will store our buy sequences and targets
    sells = []  # list that will store our sell sequences and targets

    for seq, target in sequential_data:  # iterate over the sequential data
        if target == 0:  # if it's a "not buy"
            sells.append([seq, target])  # append to sells list
        elif target == 1:  # otherwise if the target is a 1...
            buys.append([seq, target])  # it's a buy!

    random.shuffle(buys)  # shuffle the buys
    random.shuffle(sells)  # shuffle the sells!

    lower = min(len(buys), len(sells))  # what's the shorter length?

    buys = buys[:lower]  # make sure both lists are only up to the shortest length.
    sells = sells[:lower]  # make sure both lists are only up to the shortest length.

    sequential_data = buys+sells  # add them together
    random.shuffle(sequential_data)  # another shuffle, so the model doesn't get confused with all 1 class then the other.

    X = []
    y = []

    for seq, target in sequential_data:  # going over our new sequential data
        X.append(seq)  # X is the sequences
        y.append(target)  # y is the targets/labels (buys vs sell/notbuy)

    return np.array(X), y  # return X and y...and make X a numpy array!

In [20]:
train_x, train_y =  preprocess_df(main_df)
validation_x, validation_y =  preprocess_df(validation_main_df)
print(f'Train: {len(train_x)}')
print(f'Sells: {train_y.count(0)} - Buys: {train_y.count(1)}\n')
print(f'Validation: {len(validation_x)}')
print(f'Sells: {validation_y.count(0)} - Buys: {validation_y.count(1)}')

Train: 1723344
Sells: 861672 - Buys: 861672

Validation: 80264
Sells: 40132 - Buys: 40132

# RNN MODEL

In [22]:
train_x.shape[1:]

(60, 7)

In [ ]:
import time

EPOCHS = 15
BATCH_SIZE = 64
NAME = f'{SEQ_LEN}-SEQ-{FUTURE_PERIOD_PREDICT}-PRED-{int(time.time())}'

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM, CuDNNLSTM, BatchNormalization 
from tensorflow.keras.callbacks import TensorBoard, ModelCheckpoint, LambdaCallback

In [ ]:
model = Sequential()
model.add(CuDNNLSTM(128, input_shape=(train_x.shape[1:]), return_sequences=True))
model.add(Dropout(0.2))
model.add(BatchNormalization())  #normalizes activation outputs, same reason you want to normalize your input data.

model.add(CuDNNLSTM(128, return_sequences=True))
model.add(Dropout(0.1))
model.add(BatchNormalization())

model.add(CuDNNLSTM(128))
model.add(Dropout(0.2))
model.add(BatchNormalization())

model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(2, activation='softmax'))

In [ ]:
opt = tf.keras.optimizers.Adam(lr=0.001, decay=1e-6)

# Compile model
model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer=opt,
    metrics=['accuracy']
)

In [ ]:
tensorboard = TensorBoard(log_dir="../files/logs/{}".format(NAME))

In [ ]:
filepath = "RNN_Final-{epoch:02d}-{val_acc:.3f}"  # unique file name that will include the epoch and the validation acc for that epoch
checkpoint = ModelCheckpoint("../files/models/checkpoints/{}.model".format(filepath, monitor='val_acc', verbose=1, save_best_only=True, mode='max')) # saves only the best ones

In [ ]:
# Train model
history = model.fit(
    train_x, train_y,
    batch_size=BATCH_SIZE,
    epochs=EPOCHS,
    validation_data=(validation_x, validation_y),
    callbacks=[tensorboard],
)

In [ ]:
# Score model
score = model.evaluate(train_x, train_y, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])
# Save model
model.save("../files/models/{}".format(NAME))

Tensorboard
- tensorboar --logdir=

In [ ]:
predicted = model.predict_classes(train_x)

In [ ]:
predicted

In [ ]:
df